// playwright.config.js
// إعداد Playwright لاختبار Next.js

/** @type {import('@playwright/test').PlaywrightTestConfig} */
const config = {
  webServer: {
    command: 'npm run dev',
    port: 3000,
    timeout: 120 * 1000,
    reuseExistingServer: !process.env.CI,
  },
  testDir: './playwright-tests',
  use: {
    baseURL: 'http://localhost:3000',
    trace: 'on-first-retry',
    // default storage state for authenticated tests; generated by playwright/generate-storage-state.mjs
    storageState: process.env.PW_STORAGE_STATE || 'playwright/.auth/patient.json',
  },
  projects: [
    { name: 'chromium', use: { browserName: 'chromium' } },
  ],
};

export default config;
