import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./theme-provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased relative overflow-x-hidden`}>
        <ThemeProvider>
        {/* Animated SVG Background */}
        <div className="fixed inset-0 -z-50 w-full h-full pointer-events-none select-none">
          <img src="/animated-bg.svg" alt="Animated Background" className="w-full h-full object-cover" draggable="false" />
        </div>
        {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
